export const SELENIUM_TAGS = {
    IDS: {
        CREATE_GAME_BUTTON: 'CREATE_GAME_BUTTON',
        JOIN_GAME_BUTTON: 'JOIN_GAME_BUTTON',
        NAME_FIELD: 'NAME_FIELD',
        JOIN_AND_SIT_BUTTON: 'JOIN_AND_SIT_BUTTON',
        START_GAME_BUTTON: 'START_GAME_BUTTON',
        CHECK_CALL_BUTTON: 'CHECK_CALL_BUTTON',
    },
    CLASSES: {},
};
