## From main directory of repository, in order to build the container, run:
## $ sudo docker build -t jpui -f Dockerfile.ui ./

## In order to run the container, run:
## $ sudo docker run -d -p <PORT>:<FEPORT> jpui
## where PORT is a port on the host machine that will be bound to the frontend server's port (3000 for dev).

FROM node:13

WORKDIR /home/vasia/dockerapps/jpui

# Copy all sources and dependency configs
COPY ui ./

RUN npm install

# Build and start the server.
CMD ["npm", "run", "start"]
