# pull official base image
FROM node:13.12.0-alpine

# set working directory
WORKDIR /jpui

# add `/app/node_modules/.bin` to $PATH
ENV PATH /jpui/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install
# RUN npm install react-scripts@3.4.1 -g --silent

# add app
COPY ui ./

# start app
RUN npm install -g serve
CMD ["serve", "-s" "build"]
