import { genRandomInt } from '../../util/util';

/* eslint-disable @typescript-eslint/camelcase */
export enum AvatarKeys {
    nun = 'nun',
    welder = 'welder',
    priest = 'priest',
    astronaut = 'astronaut',
    ninja = 'ninja',
    soldier = 'soldier',
    cooker = 'cooker',
    diver = 'diver',
    farmer = 'farmer',
    soak = 'soak',
    postman = 'postman',
    hacker = 'hacker',
    doctor = 'doctor',
    elegance = 'elegance',
    gambler = 'gambler',
    'gambler-1' = 'gambler-1',
    king = 'king',
    queen = 'queen',
    armor = 'armor',
    executioner = 'executioner',
    jester = 'jester',
    'frog-prince' = 'frog-prince',
    dinosaur = 'dinosaur',
    shark = 'shark',
    whale = 'whale',
    penguin = 'penguin',
    gnome = 'gnome',
    chicken = 'chicken',
    horse = 'horse',
    robot = 'robot',
    'robot-1' = 'robot-1',
    'robot-2' = 'robot-2',
    'robot-3' = 'robot-3',
    'robot-4' = 'robot-4',
    alien = 'alien',
    dracula = 'dracula',
    'hip-hop' = 'hip-hop',
    batman = 'batman',
    spiderman = 'spiderman',
    dancer = 'dancer',
    'old-man' = 'old-man',
    woman = 'woman',
    grandmother = 'grandmother',
    grandfather = 'grandfather',
    'arab-woman' = 'arab-woman',
    shirt = 'shirt',
}

export enum AnimojiKeys {
    // faces
    smiling_face = 'smiling_face',
    frowning_face = 'frowning_face',
    sleeping_face = 'sleeping_face',
    winking_face = 'winking_face',
    face_with_tears_of_joy = 'face_with_tears_of_joy',
    woozy_face = 'woozy_face',
    smirking_face = 'smirking_face',
    unamused_face = 'unamused_face',
    smiling_face_with_heart_eyes = 'smiling_face_with_heart_eyes',
    face_with_symbols_on_mouth = 'face_with_symbols_on_mouth',
    cold_face = 'cold_face',
    face_vomiting = 'face_vomiting',
    pleading_face = 'pleading_face',
    loudly_crying_face = 'loudly_crying_face',
    pouting_face = 'pouting_face',
    partying_face = 'partying_face',
    exploding_head = 'exploding_head',
    grinning_face_with_smiling_eyes = 'grinning_face_with_smiling_eyes',
    smiling_face_with_hearts = 'smiling_face_with_hearts',
    shushing_face = 'shushing_face',
    zipper_mouth_face = 'zipper_mouth_face',
    money_mouth_face = 'money_mouth_face',
    rolling_on_the_floor_laughing = 'rolling_on_the_floor_laughing',
    weary_face = 'weary_face',
    lying_face = 'lying_face',
    sneezing_face = 'sneezing_face',
    thinking_face = 'thinking_face',
    smiling_face_with_halo = 'smiling_face_with_halo',
    grinning_squinting_face = 'grinning_squinting_face',
    face_with_head_bandage = 'face_with_head_bandage',
    face_screaming_in_fear = 'face_screaming_in_fear',
    crying_face = 'crying_face',
    smiling_face_with_sunglasses = 'smiling_face_with_sunglasses',
    relieved_face = 'relieved_face',

    // animals
    spouting_whale = 'spouting_whale',
    fish = 'fish',
    fishing_pole = 'fishing_pole',
    see_no_evil_monkey = 'see_no_evil_monkey',
    sloth = 'sloth',
    snake = 'snake',
    robot = 'robot',
    penguin = 'penguin',
    unicorn = 'unicorn',

    // hands & ppl
    person_shrugging = 'person_shrugging',
    person_facepalming = 'person_facepalming',
    eyes = 'eyes',
    handshake = 'handshake',
    crossed_fingers = 'crossed_fingers',
    backhand_index_pointing_right = 'backhand_index_pointing_right',
    clapping_hands = 'clapping_hands',
    flexed_biceps = 'flexed_biceps',
    middle_finger = 'middle_finger',
    thumbs_up = 'thumbs_up',
    thumbs_down = 'thumbs_down',

    // things
    money_with_wings = 'money_with_wings',
    slot_machine = 'slot_machine',
    pile_of_poo = 'pile_of_poo',
    fire = 'fire',
    popcorn = 'popcorn',
    clock = 'clock',
    violin = 'violin',
    sparkling_heart = 'sparkling_heart',
    broken_heart = 'broken_heart',
    light_bulb = 'light_bulb',
    flag_in_hole = 'flag_in_hole',
    roller_coaster = 'roller_coaster',
    trophy = 'trophy',
    pistol = 'pistol',
    rocket = 'rocket',
    bomb = 'bomb',
    fireworks = 'fireworks',
    hundred_points = 'hundred_points',
}

export const AnimojiKeysDefaultRecentlyUsed = [
    AnimojiKeys.grinning_squinting_face,
    AnimojiKeys.smiling_face_with_sunglasses,
    AnimojiKeys.exploding_head,
    AnimojiKeys.winking_face,
    AnimojiKeys.money_with_wings,
    AnimojiKeys.fishing_pole,
];

export function getRandomAvatarKey(): AvatarKeys {
    const AvatarVals = Object.values(AvatarKeys);
    const r = genRandomInt(0, AvatarVals.length - 1);
    return Object.values(AvatarKeys)[r];
}
